### ISSUE TITLE
Is there a way to easily add a new line in the default message?

### ISSUE THREAD

**Issue by atecey** [kuuurt13/ng-block-ui#59]
For example:

"This is my message"
"Status displayed Below it"

But the string sent to the block UI service is "This is my message \n Status displayed Below it"

**Comment by kuuurt13** [comment]
@atecey you would need to add a css style to render the line break. Keep the `\n` but add the below css to target the message and the line break will render correctly.

```css
.block-ui-spinner > .message {
  white-space: pre-line;
}
```
