### ISSUE TITLE
how to disable just the spinner and show only message ? 

### ISSUE THREAD

**Issue by kosnkow** [kuuurt13/ng-block-ui#84]
how to disable just the spinner and show only message ?

**Comment by kuuurt13** [comment]
@kosnkow you can just use css to hide it or do a custom template.

```css
div.block-ui-wrapper .loader {
  display: none;
}
```
